### ISSUE TITLE
some components ignores toleration config

### ISSUE THREAD

**Issue by sneerin** [druid-io/druid-operator#151]
This source works fine:
```
  nodes:
    brokers:
      nodeType: "broker"
      tolerations:
      - key: "druid"
        operator: "Equal"
        value: "pool"
        effect: "NoSchedule"      
```
this one doesn't
```
coordinators:
      nodeType: "coordinator"
      tolerations:
      - key: "druid"
        operator: "Equal"
        value: "pool"
        effect: "NoSchedule"
```
