### ISSUE TITLE
HPA doesn't work with operator v0.0.5

### ISSUE THREAD

**Issue by connie-ru-wang** [druid-io/druid-operator#160]
Using an HPA with operator v0.0.5 doesn't work because the operator immediately tries to reconcile the deployment/statefulset back to the original replica count. Most likely due to PR https://github.com/druid-io/druid-operator/pull/115

The HPA works as expected with operator v0.0.4. 

Sample HPA spec from druid cluster.yaml: 
```
      hpAutoscaler:
        maxReplicas: 6
        minReplicas: 3
        scaleTargetRef:
           apiVersion: apps/v1
           kind: Deployment
           name: druid-cluster-brokers
        metrics:
         - type: Resource
           resource:
            name: cpu
            targetAverageUtilization: 50
```
