### ISSUE TITLE
permission denied error when using default securityContext in tiny-cluster example

### ISSUE THREAD

**Issue by Murat0zer** [druid-io/druid-operator#18]
I am using [kind](https://kind.sigs.k8s.io/) to try somethings. 
well, when i deploy tiny-cluster example with default values, [init script](https://github.com/apache/druid/blob/master/distribution/docker/druid.sh)  of docker image fails.

`mkdir -p var/tmp var/druid/segments var/druid/indexing-logs var/druid/task var/druid/hadoop-tmp var/druid/segment-cache`

Above part of init scripts fail with error "permission denied cannot create directory".
when i run  containers as root (i have changed securityContext.runAsUser value to 0) everthing works as expected.
Am i doing something wrong ?

**Comment by himanshug** [comment]
following should also work and a bit safer...

```
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000
```

however, I see  that is already there in tiny cluster example ... did that not work ?  if not, can you provide full spec passed to operator ?

**Comment by Murat0zer** [comment]
yes that didnt work. i used mostly default values in the tiny-cluster.yaml . followed "Deploying druid-operator on kubernetes" and "Deploy a druid cluster" sections from README.

operatorl.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: druid-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: druid-operator
  template:
    metadata:
      labels:
        name: druid-operator
    spec:
      serviceAccountName: druid-operator
      containers:
        - name: druid-operator
          # Replace this with the built image name
          image: druidio/druid-operator:0.0.1
          command:
          - druid-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "druid-operator"

```

here is my tiny-cluster.yaml

```
apiVersion: "druid.apache.org/v1alpha1"
kind: "Druid"
metadata:
  name: tiny-cluster
spec:
  image: apache/incubator-druid:0.16.0-incubating
  startScript: /druid.sh
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000
  services:
    - spec:
        type: ClusterIP
        clusterIP: None
  commonConfigMountPath: "/opt/druid/conf/druid/cluster/_common"
  jvm.options: |-
    -server
    -XX:MaxDirectMemorySize=4096g
    -Duser.timezone=UTC
    -Dfile.encoding=UTF-8
    -Dlog4j.debug
    -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
  log4j.config: |-
    <?xml version="1.0" encoding="UTF-8" ?>
    <Configuration status="WARN">
        <Appenders>
            <Console name="Console" target="SYSTEM_OUT">
                <PatternLayout pattern="%d{ISO8601} %p [%t] %c - %m%n"/>
            </Console>
        </Appenders>
        <Loggers>
            <Root level="info">
                <AppenderRef ref="Console"/>
            </Root>
        </Loggers>
    </Configuration>
  common.runtime.properties: |

    # Zookeeper
    druid.zk.service.host=tiny-cluster-zk-0.tiny-cluster-zk
    druid.zk.paths.base=/druid
    druid.zk.service.compress=false

    # Metadata Store
    druid.metadata.storage.type=derby
    druid.metadata.storage.type=derby
    druid.metadata.storage.connector.connectURI=jdbc:derby://localhost:1527/var/druid/metadata.db;create=true
    druid.metadata.storage.connector.host=localhost
    druid.metadata.storage.connector.port=1527
    druid.metadata.storage.connector.createTables=true

    # Deep Storage
    druid.storage.type=local
    druid.storage.storageDirectory=/druid/data/deepstorage

    #
    # Extensions
    #
    druid.extensions.loadList=["druid-s3-extensions"]

    #
    # Service discovery
    #
    druid.selectors.indexing.serviceName=druid/overlord
    druid.selectors.coordinator.serviceName=druid/coordinator
  nodes:
    brokers:
      nodeType: "broker"
      druid.port: 8088
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/query/broker"
      replicas: 1
      runtime.properties: |
        druid.service=druid/broker
        druid.plaintextPort=8082

        # HTTP server settings
        druid.server.http.numThreads=6

        # HTTP client settings
        druid.broker.http.numConnections=5
        druid.broker.http.maxQueuedBytes=5000000

        # Processing threads and buffers
        druid.processing.buffer.sizeBytes=50000000
        druid.processing.numMergeBuffers=2
        druid.processing.numThreads=1
        druid.processing.tmpDir=var/druid/processing

        # Query cache disabled -- push down caching and merging instead
        druid.broker.cache.useCache=false
        druid.broker.cache.populateCache=false
      extra.jvm.options: |-
        -server
        -Xms128m
        -Xmx512m
        -XX:MaxDirectMemorySize=400m
        -XX:+ExitOnOutOfMemoryError
        -XX:+UseG1GC
        -Duser.timezone=UTC
        -Dfile.encoding=UTF-8
        -Djava.io.tmpdir=/tmp/druid
        -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
      volumeMounts:
        - mountPath: /druid/data
          name: data-volume
      volumes:
        - name: data-volume
          emptyDir: {}
      resources:
        requests:
          memory: "2G"
          cpu: "2"
        limits:
          memory: "2G"
          cpu: "2"

    coordinators:
      nodeType: "coordinator"
      druid.port: 8088
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/master/coordinator-overlord"
      replicas: 1
      runtime.properties: |
        druid.service=druid/coordinator

        # HTTP server threads
        druid.coordinator.startDelay=PT30S
        druid.coordinator.period=PT30S

        # Configure this coordinator to also run as Overlord
        druid.coordinator.asOverlord.enabled=true
        druid.coordinator.asOverlord.overlordService=druid/overlord
        druid.indexer.queue.startDelay=PT30S
        druid.indexer.runner.type=local
      extra.jvm.options: |-
        -Xmx1G
        -Xms1G
      volumeMounts:
        - mountPath: /druid/data
          name: data-volume
      volumes:
        - name: data-volume
          emptyDir: {}
      resources:
        requests:
          memory: "2G"
          cpu: "2"
        limits:
          memory: "2G"
          cpu: "2"

    historicals:
      nodeType: "historical"
      druid.port: 8088
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/data/historical"
      replicas: 1
      runtime.properties: |
        druid.service=druid/historical
        druid.server.http.numThreads=5
        druid.processing.buffer.sizeBytes=1
        druid.processing.numMergeBuffers=1
        druid.processing.numThreads=1
        # Segment storage
        druid.segmentCache.locations=[{\"path\":\"/druid/data/segments\",\"maxSize\":10737418240}]
        druid.server.maxSize=10737418240
      extra.jvm.options: |-
        -Xmx1G
        -Xms1G
      volumeMounts:
        - mountPath: /druid/data
          name: data-volume
      volumes:
        - name: data-volume
          emptyDir: {}
      resources:
        requests:
          memory: "2G"
          cpu: "2"
        limits:
          memory: "2G"
          cpu: "2"
    routers:
      nodeType: "router"
      druid.port: 8888
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/query/router"
      replicas: 1
      runtime.properties: |
        druid.service=druid/router
        druid.plaintextPort=8888

        # HTTP proxy
        druid.router.http.numConnections=50
        druid.router.http.readTimeout=PT5M
        druid.router.http.numMaxThreads=100
        druid.server.http.numThreads=100

        # Service discovery
        druid.router.defaultBrokerServiceName=druid/broker
        druid.router.coordinatorServiceName=druid/coordinator

        # Management proxy to coordinator / overlord: required for unified web console.
        druid.router.managementProxy.enabled=true        
        
      extra.jvm.options: |-
        -server
        -Xms1g
        -Xmx1g
        -XX:+UseG1GC
        -XX:MaxDirectMemorySize=128m
        -XX:+ExitOnOutOfMemoryError
        -Duser.timezone=UTC
        -Dfile.encoding=UTF-8
        -Djava.io.tmpdir=var/tmp
        -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
```
