### ISSUE TITLE
Validation Error on the HPA specification

### ISSUE THREAD

**Issue by layoaster** [druid-io/druid-operator#181]
I'm using the new `autoscaling/v2beta2` spec for HPAs but for some reason I'm getting validation errors with the new specification:

```
ValidationError(Druid.spec.nodes.brokers.hpAutoscaler.metrics[0].resource): unknown field "target" in org.apache.druid.v1alpha1.Druid.spec.nodes.hpAutoscaler.metrics.resource, 
ValidationError(Druid.spec.nodes.brokers.hpAutoscaler.metrics[1].resource): unknown field "target" in org.apache.druid.v1alpha1.Druid.spec.nodes.hpAutoscaler.metrics.resource, 
```

```yaml
nodes:
    ############################## Druid Query #################################
    brokers:
      # Optionally specify for running broker as Deployment
      # kind: Deployment
      nodeType: "broker"
      # Optionally specify for broker nodes
      # imagePullSecrets:
      # - name: tutu
      druid.port: 8088
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/query/broker"
      replicas: 1
      podDisruptionBudgetSpec:
        maxUnavailable: 1
      extra.jvm.options: |-
        -Xmx2G
        -Xms2G
      runtime.properties: |
        # https://druid.apache.org/docs/latest/configuration/index.html#broker
        druid.service=druid/broker
        druid.plaintextPort=8088
        # HTTP server
        druid.server.http.numThreads=30
        # HTTP Client
        druid.broker.http.numConnections=20
        # Processing threads and buffers
        druid.processing.buffer.sizeBytes=256MiB
        druid.processing.numMergeBuffers=1
        druid.processing.numThreads=1
        druid.sql.enable=true
        druid.processing.tmpDir=/druid/data/processing
      resources:
        limits:
          cpu: "2"
          memory: 6Gi
        requests:
          cpu: "2"
          memory: 6Gi
      hpAutoscaler:
        scaleTargetRef:
           apiVersion: apps/v1
           kind: StatefulSet
           name: druid-cluster-brokers
        minReplicas: 1
        maxReplicas: 6
        metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 60
          - type: Resource
            resource:
              name: memory
              target:
                type: Utilization
                averageUtilization: 60
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - druid-query
```

The `target` field is defined according to [official spec](https://pkg.go.dev/k8s.io/api/autoscaling/v2beta2#ResourceMetricSource) so I don't know what I am missing

**Environment:**
* I have installed the operator with the helm chart provided on the repo
* druid-operator image: `druidio/druid-operator:0.0.6`
* kubctl version:
```
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:13:28Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-22T22:54:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
