### ISSUE TITLE
Druid services on Internal LoadBalancer

### ISSUE THREAD

**Issue by soumyajose0784** [druid-io/druid-operator#183]
Is there a sample yaml for tiny_cluster.yaml with services exposed on 'Internal LoadBalancer'. We were able to change the type from clusterIP to loadbalancer but services are started on 'External LoadBalancer IP instead of internal IP.  We tried specifying annotation(networking.gke.io/load-balancer-type: "Internal") in services section but didn't help.

**Comment by AdheipSingh** [comment]
@soumyajose0784 
As far the operator is concerned it accepts a service for each nodeType, ie exactly same as a service yaml.  Can you confirm if the annotations you passed in the DRUID CR are getting reflected in the actual service creation ? 
Example on how it can be added in inside the operator spec.
```
       services:
        - metadata:
            annotations:
              ad.datadoghq.com/service.check_names: '["http_check"]'
            labels:
              app: druid
              environment: stage
            name: router
          spec:
            ports:
            - name: http
              port: 8080
              protocol: TCP
              targetPort: 8080
            type: ClusterIP
     ```
