### ISSUE TITLE
Issue with ingress not being created

### ISSUE THREAD

**Issue by layoaster** [druid-io/druid-operator#216]
Environment:
* Kubernetes `v1.19`
* `druid-operator`: `v0.0.6.1` with helm chart from *master*

I kept getting the following issue when creating an ingress resource for the router:
```
 Warning  CREATE_FAIL     63s   druid-operator  Failed to create [Ingress:druid-staging-routers] due to [Ingress.extensions "druid-staging-routers" is invalid: spec.rules[0].http.paths[0].backend: Invalid value: "": resource or service backend is required].
```

I have the following in the **router** section of the spec:

```yaml
    routers:
      nodeType: "router"

      ....

      services:
        - spec:
            type: ClusterIP
            ports:
              - name: http
                port: 80
                targetPort: 8888


      ingressAnnotations:
        cert-manager.io/issuer: "letsencrypt-staging"
      ingress:
        ingressClassName: nginx
        tls:
        - hosts:
          - staging.druid.s73cloud.com
          secretName: tls-router-druid-cluster
        rules:
          - host: staging.druid.s73cloud.com
            http:
              paths:
                - path: /
                  pathType: ImplementationSpecific
                  backend:
                    service:
                      name: druid-staging-routers
                      port:
                        name: http
```
