### ISSUE TITLE
Auto-scaling issues

### ISSUE THREAD

**Issue by EwanValentine** [druid-io/druid-operator#246]
I'm doing some load-testing at the moment. I'm using Gatling to scale requests per second up from 100 to 1000 over the course of around four minutes. 

However, I start to run into connection errors, where the router seems to get overwhelmed. I've got an HPA setup for each component. I've tried multiple settings and scaling rules based on average CPU and memory utilisation. The router's running on an `r5.xlarge`. 

Looking at the resource usage, I start getting connection errors long before the HPA kicks in. The CPU didn't exceed 16%, and the memory hovered around 20%. Then all the requests start to fail. So it's like it's not utilising the available resources before hitting limits. 

Here's my current router config: 

```
routers:
      extra.jvm.options: |-
        -Xms256M
        -Xmx2G
      hpAutoscaler:
        behavior:
          scaleDown:
            stabilizationWindowSeconds: 60
            policies:
            - type: Percent
              value: 50
              periodSeconds: 15
        maxReplicas: {{ default .Values.routers.maxReplicas 5 }}
        minReplicas: 1
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: druid-druid-cluster-routers
        metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 60
          - type: Resource
            resource:
              name: memory 
              target:
                type: Utilization 
                averageUtilization: 40
      kind: {{ default .Values.routers.kind "Deployment" }}
      maxSurge: 2
      maxUnavailable: 0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: service
                    operator: In
                    values:
                      - {{ .Values.computeTierNodeSelector }}
      livenessProbe:
        initialDelaySeconds: 10
        periodSeconds: 1
        failureThreshold: 10
        httpGet:
          path: /status/health
          port: {{ default .Values.routers.port 8080 }}
      readinessProbe:
        initialDelaySeconds: 10
        periodSeconds: 1
        failureThreshold: 10
        httpGet:
          path: /status/health
          port: {{ default .Values.routers.port 8080 }}
      druid.port: {{ default .Values.routers.port 8080 }}
      env:
        - name: AWS_REGION
          value: {{ default .Values.region "eu-west-1" }}
        - name: AWS_DEFAULT_REGION
          value: {{ default .Values.region "eu-west-1" }}
      resources:
        limits:
          cpu: {{ default .Values.routers.resources.maxCPU 2 }}
          memory: {{ default .Values.routers.resources.maxMemory "2Gi" }}
        requests:
          cpu: {{ default .Values.routers.resources.desiredCPU 2 }}
          memory: {{ default .Values.routers.resources.desiredMemory "2Gi" }}
      nodeType: router
      podDisruptionBudgetSpec:
        maxUnavailable: 1
      nodeConfigMountPath: /opt/druid/conf/druid/cluster/query/router
      replicas: {{ default .Values.routers.replicas 1 }}
      runtime.properties: |
          druid.service=druid/router
          druid.log4j2.sourceCategory=druid/router

          druid.router.http.numConnections=4
          druid.router.http.readTimeout=PT5M
          druid.router.http.numMaxThreads=10
          druid.server.http.numThreads=10

          # Service discovery
          druid.router.defaultBrokerServiceName=druid/broker
          druid.router.coordinatorServiceName=druid/coordinator
          druid.router.managementProxy.enabled=true
      {{ with .Values.routers.service -}}
      services:
        -
          metadata:
            name: router-%s-service
          spec:
            ports:
              -
                name: router-port
                port: {{ default .port 8080 }}
            type: {{ default .type "NodePort" }}
      {{- end }}
```

I've tried tweaking connection and thread limits (from low to really high, like 1000). I've tried tweaking the Xms and Xmx values to in theory allow the heap to grow in relation to the K8s max memory values. Given the current values, I'd expect the utilisation to increase with the number of requests and the auto-scaling to kick in. But it doesn't seem to budge! Any suggestions or advice? 

I've posted about it in more detail on the Druid forums: https://www.druidforum.org/t/router-scaling-issues/6664 

But haven't had a response yet. 

Thanks in advance!
