### ISSUE TITLE
Proposal: Add sidecar to Druid deployments

### ISSUE THREAD

**Issue by cintoSunny** [druid-io/druid-operator#293]
**MOTIVATION**

Currently, the Druid operator does not allow the addition of a sidecar container to Druid deployments. The only way is to inject sidecars by mutation webhooks like istio. But many orgs may not allow setting up istio or it could be an additional effort to add them. 

**PROPOSAL**
To have the ability to add sidecars via druid operator based on a set of configs. The configs can look something like this: 
```
sidecarContainer:
- configs:
    imageName: docker.com/ns/samplesimage:latest
    containerName: sidecar
    command: /bin/start.sh
    pullPolicy: Always
...

```
I have a working code for my org that I used for logging. And can push the change here, but wanted to check with the community first. I saw a couple of issues regarding this earlier, so thought it would be useful. cc: @AdheipSingh
