### ISSUE TITLE
Allow possibilities to add env var to erase some config value

### ISSUE THREAD

**Issue by vDMG** [druid-io/druid-operator#35]
## Context
Today, all our password are in clear in our configuration, which is not a good securiy practice.
**example**
```
druid.metadata.storage.connector.password=toto
druid.zk.service.pwd
```

## Proposal

We could allow user to specify somme environment variable to erase some values
**example**
```
env:
- name: DRUID_METADATA_STORAGE_CONNECTOR_PASSWORD
   valueFrom:
     secretKeyRef:
       name: druid-connector
       key: password
```

We could imagine to replace after those values in the configuration.
We need to define stricts norms for those environment variables ("\_" replace ".",all upper case and starting with "DRUID_".

----
 
What are your thoughts about this idea ? @himanshug @AdheipSingh

**Comment by AdheipSingh** [comment]
Hey @vDMG 
Here is a workaround
```
druid.metadata.storage.connector.password={"type":"environment","variable":"CONNECTOR_KEY"}
```
then use this as an env
```
env:
  - name: CONNECTOR_KEY
    valueFrom:
      secretKeyRef:
        key: db-password
        name: druid-secrets
```
