### ISSUE TITLE
nodeSelector not working

### ISSUE THREAD

**Issue by sc7565** [druid-io/druid-operator#38]
with below....

```
kind: "Druid"
metadata:
  name: tiny-cluster
spec:
  image: apache/incubator-druid:0.16.0-incubating
  startScript: /druid.sh
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000
  services:
    - spec:
        type: ClusterIP
        clusterIP: None
  nodeSelector:
    type: "druid"
  commonConfigMountPath: "/opt/druid/conf/druid/cluster/_common"
....
```
