### ISSUE TITLE
middlemanager graceful termination

### ISSUE THREAD

**Issue by exherb** [druid-io/druid-operator#60]
https://druid.apache.org/docs/latest/operations/rolling-updates.html#rolling-restart-graceful-termination-based

add support to customize preStop?

```yaml
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 4200
      containers:
      - name: druid-xapi-druid-middlemanagers
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - |
                wget --post-data='{}' -q -O - http://localhost:8088/druid/worker/v1/disable > /dev/null && while [[ "$(wget -q -O - http://localhost:8088/druid/worker/v1/tasks)" != "[]" ]]; do sleep 10; done

```
