### ISSUE TITLE
CR not Giving status

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#77]
1. The CRD has been missing this part which is responsible for status
```
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```
2. To know what state is in druid cluster, we have events but they only print on CRUD events. ( and describe of cr ) . So we are updating the status but some its now coming up when to doing ```kubectl get druid my-druid -o yaml -n my-namespace```
![image](https://user-images.githubusercontent.com/34169002/92478434-c4448200-f1ff-11ea-8f3f-1d2fec5563c0.png)

In the above shot, we are not getting status, basically all k8s objects using runtime.object interface are responsible sending out a status which can also be polled /status endpoint. 

Just curious is this something we did on purpose or missed out in the CRD spec.
Ill be evaulting and fixing this anyways. :) 
 @himanshug
